language: ruby
addons:
  postgresql: "9.4"
rvm:
 - "2.0.0"
cache: bundler
before_script:
  - bundle install
  - psql -c 'create database your_priorities_test;' -U postgres
  - bundle exec rake db:setup
script: bundle exec rake
